#3 .application-prod.yml (Docker / Production)

spring:
  datasource:
#    url: jdbc:postgresql://db:5432/supportdesk
    url: jdbc:postgresql://db.mchemprcytszpobfzueu.supabase.co:5432/postgres?user=postgres&password=Shubham@3133
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  ai:
    gemini:
      api-key: ${GEMINI_API_KEY}

server:
  port:8080